spring:
  application:
    name: ph-oauth-server

server:
  port: 10005

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.boot.actuate.audit.listener.AuditListener: DEBUG

security:
  basic:
    enabled: false