spring:
  application:
    name: ph-eureka-server
server:
  port: 10001
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
logging:
  level: 
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF